# ~/.config/kitty/startup.conf
# "Kitty" Window
## Tab 1 | Home
new_tab Home
launch --hold /opt/homebrew/opt/zsh/bin/zsh -c 'echo -n "\033]0;Kitty | Home\007"'
## Tab 2 | Neovim
new_tab Neovim
launch --hold /opt/homebrew/opt/zsh/bin/zsh -c 'echo -n "\033]0;Kitty | Neovim\007" && nvim -c ":cd .config/nvim"'
## Tab 3 | configuration-files
new_tab configuration-files
launch --hold /opt/homebrew/opt/zsh/bin/zsh -c 'echo -n "\033]0;Kitty | configuration-files\007" && nvim -c ":cd Configuration\ Files" -c :terminal -c startinsert'
## Tab 4 | my-kickstart.nvim
new_tab my-kickstart.nvim
launch --hold /opt/homebrew/opt/zsh/bin/zsh -c 'echo -n "\033]0;Kitty | my-kickstart.nvim\007" && nvim -c ":cd .config/nvim" -c :terminal -c startinsert'
