# ~/.config/kitty/startup.conf
# Launch tabs
## Tab 1 | Zsh
new_tab Zsh
launch --title='Kitty | Zsh' --cwd="$HOME" /opt/homebrew/opt/zsh/bin/zsh -ci 'clear && exec zsh'

## Tab 2 | configuration-files
new_tab configuration-files
launch --title='Kitty | configuration-files' --cwd="$HOME/Configuration Files" /opt/homebrew/opt/zsh/bin/zsh -ci 'nvim -c :terminal -c startinsert && exec zsh'

## Tab 3 | my-kickstart.nvim
new_tab my-kickstart.nvim
launch --title='Kitty | my-kickstart.nvim' --cwd="$HOME/.config/nvim" /opt/homebrew/opt/zsh/bin/zsh -ci 'nvim -c :terminal -c startinsert && exec zsh'
