# ~/.config/kitty/startup.conf
# "Kitty" Window
## Tab 1 | Home
new_tab Home
cd '/Users/Nyx/Configuration Files'
launch --hold /opt/homebrew/opt/zsh/bin/zsh -c 'echo -n "\033]0;Kitty | Home\007"'
## Tab 2 | Neovim
new_tab Neovim
cd '/Users/Nyx/Configuration Files'
launch --hold /opt/homebrew/opt/zsh/bin/zsh -c 'echo -n "\033]0;Kitty | Neovim\007" && nvim'
## Tab 3 | Configs Repo
new_tab Configs Repo
launch --hold /opt/homebrew/opt/zsh/bin/zsh -c 'echo -n "\033]0;Kitty | Configuration Files\007" && nvim -c ":cd Configuration\ Files" -c :terminal -c startinsert'